#!/usr/bin/env python

import rospy
from std_srvs.srv import Empty


def rotate_client():
    rospy.wait_for_service('clear_checkpoint')
    checkpoint = rospy.ServiceProxy('clear_checkpoint', Empty)
    checkpoint()


if __name__ == "__main__":
    rospy.init_node('clear_checkpoint_client')
    rotate_client()
