#!/usr/bin/env python
import json
import sys
import math
import rospy
import tf2_ros
import tf2_geometry_msgs
from tf.transformations import euler_from_quaternion
from geometry_msgs.msg import PoseStamped, Vector3
from std_msgs.msg import Empty
from crazyflie_driver.msg import Position
from crazyflie_driver.msg import Hover
from tf2_msgs.msg import TFMessage


goal = None
stop = None


def get_stop(stop_cmd):
    global stop
    stop = stop_cmd


def cmd_callback(msg):
    global goal
    goal = msg


pub_cmd = rospy.Publisher('/cf1/cmd_position', Position, queue_size=2)
sub_cmd = rospy.Subscriber('keyboardControlPosition', Position, cmd_callback)
sub_stop = rospy.Subscriber('stop', Empty, get_stop)

rospy.init_node('hoverDrone', anonymous=True)


if __name__ == '__main__':
    rate = rospy.Rate(10)

    while goal == None and not rospy.is_shutdown(): # Wait for 1st goal to be received
        continue

    while not rospy.is_shutdown():
        rate.sleep()
        if stop:
            break
        rospy.loginfo(goal)
        pub_cmd.publish(goal)
